version: "3"
services:
  aaa:
    image: golang:1.16-alpine
    volumes:
      - ./../../:/httpclient
    environment:
      SERVICE_NAME: "aaa"
      SERVICE_HOST: ":8080"
    working_dir: /httpclient/examples/clientDebug/service
    command: go run main.go
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - code-network

  bbb:
    image: golang:1.16-alpine
    volumes:
      - ./../../:/httpclient
    environment:
      SERVICE_NAME: "bbb"
      SERVICE_HOST: ":8081"
    working_dir: /httpclient/examples/clientDebug/service
    command: go run main.go
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - code-network

  ccc:
    image: golang:1.16-alpine
    volumes:
      - ./../../:/httpclient
    environment:
      SERVICE_NAME: "ccc"
      SERVICE_HOST: ":8082"
    working_dir: /httpclient/examples/clientDebug/service
    command: go run main.go
    ports:
      - "8082:8082"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
